### ISSUE TITLE
To-do for project (updated Jan 3)

### ISSUE THREAD

**Issue by L-Buchholz** [collink91/mile-hi#20]
Based on Project 2 requirements PowerPoint

Front end: 
- [x] Get Handlebars working!
- [x] Add user sign-up html: Inc. user name, email, and password
- [x] Add user login/authorization html to fulfill authentication: Inc. email and password (not user name)
- [x] Ensure sign-up/login-pages sync with Handlebars
- [x] Add user "POST" new activity HTML page (currently works in Insomnia)
- [x] Ensure new activity (POST) page syncs with Handlebars
- [x] Clean up form entries and "Login"/"Create new activity" buttons
- [x] Clean up "Login"/"Create new activity" forms

Front and back end:
- [x] Create .js in utils (public) folder that enables user authorization to be called in activitiesRoutes
- [x] New library, package, or technology: Need to add one per the requirement to use something we haven't discussed in class
- [ ] _OPTIONAL: Complete routes for user "Logout"_
- [ ] _OPTIONAL: Search bar (create HTML and searchRoutes.js)_

Back end:

- [x] Add user sign-up and ensure it's authorized (using express-session and cookies)
- [x] Ensure user login/authorization is protected (using express-session and cookies)
- [x] Ensure user "POST" and create account/sign-in routes that require authorization are protected (i.e.: `if (!req.session.loggedIn)...`, currently on activitiesRoutes.js)

AT THE END:

- [x] Make sure Heroku and all data has been properly deployed via @LutzJason92's  account
- [x] Update and finalize README [Cray]
- [x] **Presentation** (check requirements)

**Comment by LutzJason92** [comment]
if thios is up to date my goal for this weekend and over the weekend is to satisfy #4 in front end, #3 in back end, and the ReadMe and and the presentation. 

Please let me know via slack if these objective has been accomplished.

**Comment by LutzJason92** [comment]
this page seemed to update after the comment was posted and #3 on the back is has been accomplished.

**Comment by L-Buchholz** [comment]
I think the main JS things now are to create a working "POST" activity page and make sure everything connects properly once a user is logged in. Otherwise, cleaning up the pages and then the "At the end" stuff. I'm leaning towards leaving the "Search" bar as an icebox at this point, but we can check in on Monday.

** The "Solved" solution for the last HW assignment (the optional one) is a really great resource, I pulled from that for my edits the other day

Looking great guys!

**Comment by L-Buchholz** [comment]
See updated checklist -- Activities form is now working

**Comment by SmithCray** [comment]
Update and finalize README all done

**Comment by SmithCray** [comment]
Presentation done
